@startuml

Interface Component {
    + getPath()
    + getName()
    + isComposite()
}

Class File implements Component {
    + getPath()
    + getName()
    + isComposite()
}

Class Directory implements Component {
    + getPath()
    + getName()
    + isComposite()
    + add(Component)
    + remove(Component)
    + getChildren()
}

Interface Command {
    + execute()
}

Interface FileSystem {
    + getRoot()
    + getCurrent()
    + setCurrent()
    + executeCommand()
}

Class MyFileSystem implements FileSystem {
    + getRoot()
    + getCurrent()
    + setCurrent()
    + executeCommand()
}

Interface CommandBuilder {
    + build()
}

Component *-- Directory
MyFileSystem *-- Component
MyFileSystem *-- CommandBuilder
CommandBuilder *-- Command

@enduml